eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    refresh:
      enable: true
    service-url:
      defaultZone: http://localhost:8081/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/practice
    username: postgres
    password: h@sib2211
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379
logging:
  level:
    web: info
