server:
  port: 8083

spring:
  profiles:
    active: staging
  banner:
    charset: UTF-8
  application:
    name: @project.artifactId@
    version: @project.version@
  main:
    web-application-type: servlet

jwt:
  secret : Y2FzYW5vYmxlLXNlY3JldC1rZXktZm9yLWp3dC1oYTUxMi1hdXRoZW50aWNhdGlvbi1zeXN0ZW0tMjAyNQ==
  expiration : 3600000